name: 'ntd - codeartifact token'
description: 'ntd - codeartifact token'
inputs:
  aws_codeartifact_domain:
    description: Your domain
    required: true
  aws_codeartifact_owner:
    description: The owner's account id
    required: true
  aws_region:
    description: AWS region
    required: true
    default: ap-southeast-1
  aws_access_key:
    description: AWS Access Key ID
    required: true
  aws_secret_key: 
    description: AWS Scret Access Key
    required: true
outputs:
  codeartifact_token: 
    description: The token to be used
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws_access_key }}
    - ${{ inputs.aws_secret_key }}
    - ${{ inputs.aws_codeartifact_domain }}
    - ${{ inputs.aws_codeartifact_owner }}
    - ${{ inputs.aws_region }}
branding:
  icon: arrow-up-circle
  color: blue
